sudo: false

dist: bionic

language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8-dev"
    - python: "nightly"
    - python: "pypy2.7-6.0"
    - python: "pypy3.5-6.0"

  # There's a Pipenv issue that currently prevents telnyx-python from building
  # properly on Pypy3:
  #
  #     https://github.com/pypa/pipenv/pull/3322
  #
  # Olivier from Stripe patched it, but we're still waiting on the Pipenv
  # project for a new release (>2018.11.26). When that happens, we can remove
  # pypy3 from this section.
  allow_failures:
    - python: "pypy3.5-6.0"
    - python: "3.4"      # not officially supported, but may as well check
    - python: "3.8-dev"  # not supported until released
    - python: "nightly"  # "may or may not, there is a try"

cache:
  directories:
    - telnyx-mock
  pip: false

env:
  global:
    # If changing this number, please also change it in `tests/conftest.py`.
    - TELNYX_MOCK_VERSION=0.1.0

before_install:
  # Unpack and start telnyx-mock so that the test suite can talk to it
  - |
    if [ ! -d "telnyx-mock/${TELNYX_MOCK_VERSION}" ]; then
      mkdir -p telnyx-mock/${TELNYX_MOCK_VERSION}
      curl -L "https://github.com/team-telnyx/telnyx-mock/releases/download/v${TELNYX_MOCK_VERSION}/telnyx-mock_${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz" -o "telnyx-mock/${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "telnyx-mock/${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz" -C "telnyx-mock/${TELNYX_MOCK_VERSION}/"
    fi
  - |
    telnyx-mock/${TELNYX_MOCK_VERSION}/telnyx-mock > /dev/null &
    TELNYX_MOCK_PID=$!
  - export PATH="${PATH}:${PWD}/telnyx-mock/${TELNYX_MOCK_VERSION}"

install:
  - make init

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then make lint; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then make fmtcheck; fi
  - make ci

after_success:
  make coveralls
